#!/usr/bin/env python3
"""Build v1.5 candidate from protected v1.4 base + isolated smart-key block."""
from __future__ import annotations
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
PROJECT = ROOT / "pine-script" / "master-smc-sats"
BASE_PATH = PROJECT / "01_BASE_WORKING_VERSION" / "master-smc-sats-ravi-custom-01-v1.4-LAST-WORKING.pine"
SMART_BLOCK_PATH = PROJECT / "03_SCRIPT_BLOCKS" / "06_smart_key_level_engine.pine"
OUT_PATH = PROJECT / "03_MASTER_CANDIDATES" / "master-smc-sats-ravi-custom-01-v1.5-smart-key-liquidity-candidate.pine"

INSERT_MARKER = "// ══════════════════════════════════════════════════════════════════════════════\n// ZONE + KEY LEVEL CONFLUENCE\n// ══════════════════════════════════════════════════════════════════════════════"
ALERTS_MARKER = "// ══════════════════════════════════════════════════════════════════════════════\n// ALERTS\n// ══════════════════════════════════════════════════════════════════════════════"
STATUS_START_MARKER = "// Mini status label"

HEADER_NOTE = """// ══════════════════════════════════════════════════════════════════════════════
// v1.5 CANDIDATE NOTE
// Generated by 03_SCRIPT_BLOCKS/98_assemble_v1_5_candidate.py
// Source base: 01_BASE_WORKING_VERSION/master-smc-sats-ravi-custom-01-v1.4-LAST-WORKING.pine
// Added: 03_SCRIPT_BLOCKS/06_smart_key_level_engine.pine
// Connection: smart key-level hooks extend, not replace, v1.4 key reactions.
// Runtime safety: empty OB/FVG visual arrays are guarded before array.get().
// Visual safety: mini status can be moved to a corner table panel.
// Smart levels: current chart timeframe pivot clusters; default selection is nearest valid support/resistance.
// Test required in TradingView before promotion to 00_MASTER_COMPILED.
// ══════════════════════════════════════════════════════════════════════════════
"""

OLD_STATUS_INPUT = 'showMiniStatus     = input.bool(true, "Show Mini Status Label", group = GRP_VIS)'
NEW_STATUS_INPUT = '''showMiniStatus     = input.bool(true, "Show Mini Status Panel", group = GRP_VIS)
miniStatusPosition = input.string("Right of Price", "Mini Status Position", options = ["Right of Price", "Top Right", "Top Left", "Bottom Right", "Bottom Left"], group = GRP_VIS, tooltip = "Right of Price keeps the original floating price-level label. Corner options use a fixed table panel so it does not sit on live price.")'''

REPLACEMENTS = [
    ("anyExistingKeyLevelTouched = currentSwingKeyTouched or currentPdPwPmTouched or currentPoiTouched or htfKey1Touched or htfKey2Touched",
     "anyExistingKeyLevelTouched = currentSwingKeyTouched or currentPdPwPmTouched or currentPoiTouched or htfKey1Touched or htfKey2Touched or smartAnyKeyTouched",
     "smart any-key hook"),
    ("     (k2_obNearDir == 1 and nearLevel(k2ObLevel)) or\n     (k2_fvgNearDir == 1 and nearLevel(k2FvgLevel)))",
     "     (k2_obNearDir == 1 and nearLevel(k2ObLevel)) or\n     (k2_fvgNearDir == 1 and nearLevel(k2FvgLevel)) or\n     smartBullKeyReaction)",
     "smart bull reaction hook"),
    ("     (k2_obNearDir == -1 and nearLevel(k2ObLevel)) or\n     (k2_fvgNearDir == -1 and nearLevel(k2FvgLevel)))",
     "     (k2_obNearDir == -1 and nearLevel(k2ObLevel)) or\n     (k2_fvgNearDir == -1 and nearLevel(k2FvgLevel)) or\n     smartBearKeyReaction)",
     "smart bear reaction hook"),
    ('''    obCount = currTfOBs.size()
    for i = 0 to obCount - 1
        ob = currTfOBs.get(i)
        obColor = ob.dir > 0 ? color.new(bullColor, 82) : color.new(bearColor, 82)
        obBorder = ob.dir > 0 ? bullColor : bearColor
        newBox = box.new(left = ob.barIdx, top = ob.top, right = bar_index + obExtend, bottom = ob.bottom, border_color = obBorder, border_width = 1, bgcolor = obColor, text = ob.dir > 0 ? "OB ↑" : "OB ↓", text_color = obBorder, text_halign = text.align_right, text_valign = text.align_center, text_size = size.small)
        obBoxes.unshift(newBox)''',
     '''    obCount = currTfOBs.size()
    if obCount > 0
        for i = 0 to obCount - 1
            ob = currTfOBs.get(i)
            obColor = ob.dir > 0 ? color.new(bullColor, 82) : color.new(bearColor, 82)
            obBorder = ob.dir > 0 ? bullColor : bearColor
            newBox = box.new(left = ob.barIdx, top = ob.top, right = bar_index + obExtend, bottom = ob.bottom, border_color = obBorder, border_width = 1, bgcolor = obColor, text = ob.dir > 0 ? "OB ↑" : "OB ↓", text_color = obBorder, text_halign = text.align_right, text_valign = text.align_center, text_size = size.small)
            obBoxes.unshift(newBox)''',
     "OB empty-array guard"),
    ('''    fvgCount = currTfFvgs.size()
    for i = 0 to fvgCount - 1
        fvg = currTfFvgs.get(i)
        fvgBg = fvg.dir > 0 ? color.new(bullColor, 87) : color.new(bearColor, 87)
        fvgBorder = fvg.dir > 0 ? color.new(bullColor, 60) : color.new(bearColor, 60)
        fvgTxt = fvg.dir > 0 ? bullColor : bearColor
        newBox = box.new(left = fvg.barIdx, top = fvg.top, right = bar_index + fvgExtend, bottom = fvg.bottom, bgcolor = fvgBg, border_width = 1, border_style = line.style_dashed, border_color = fvgBorder, text = fvg.dir > 0 ? "FVG ↑" : "FVG ↓", text_color = fvgTxt, text_halign = text.align_right, text_valign = text.align_center, text_size = size.small)
        fvgBoxes.unshift(newBox)''',
     '''    fvgCount = currTfFvgs.size()
    if fvgCount > 0
        for i = 0 to fvgCount - 1
            fvg = currTfFvgs.get(i)
            fvgBg = fvg.dir > 0 ? color.new(bullColor, 87) : color.new(bearColor, 87)
            fvgBorder = fvg.dir > 0 ? color.new(bullColor, 60) : color.new(bearColor, 60)
            fvgTxt = fvg.dir > 0 ? bullColor : bearColor
            newBox = box.new(left = fvg.barIdx, top = fvg.top, right = bar_index + fvgExtend, bottom = fvg.bottom, bgcolor = fvgBg, border_width = 1, border_style = line.style_dashed, border_color = fvgBorder, text = fvg.dir > 0 ? "FVG ↑" : "FVG ↓", text_color = fvgTxt, text_halign = text.align_right, text_valign = text.align_center, text_size = size.small)
            fvgBoxes.unshift(newBox)''',
     "FVG empty-array guard"),
]

NEW_STATUS_BLOCK = '''// Mini status panel
// v1.5: selectable placement. "Right of Price" keeps the original floating label.
// Corner positions use tables, so the panel does not sit directly on live price.
var label statusLabel = na
var table statusTopRight = table.new(position.top_right, 1, 1)
var table statusTopLeft = table.new(position.top_left, 1, 1)
var table statusBottomRight = table.new(position.bottom_right, 1, 1)
var table statusBottomLeft = table.new(position.bottom_left, 1, 1)

clearStatusTable(table tbl) =>
    table.cell(tbl, 0, 0, "", text_color = color.new(color.white, 100), bgcolor = color.new(color.black, 100), text_size = size.small)

drawStatusTable(table tbl, string txt) =>
    table.cell(tbl, 0, 0, txt, text_color = color.white, bgcolor = color.new(color.black, 20), text_size = size.small, text_halign = text.align_left)

if barstate.islast
    label.delete(statusLabel)
    clearStatusTable(statusTopRight)
    clearStatusTable(statusTopLeft)
    clearStatusTable(statusBottomRight)
    clearStatusTable(statusBottomLeft)

    if showMiniStatus
        biasTxt = htfBullishBias ? "Bull" : htfBearishBias ? "Bear" : "Neutral"
        statusTxt = "Preset: " + masterPreset +
          "\\nBias: " + biasTxt + " (" + str.tostring(biasPct, "#.0") + "%)" +
          "\\nKZ: " + killzoneName + " | " + (killzoneAllowed ? "OK" : "BLOCK") + (effectiveKillzoneOnly and killzoneName == "NO KILLZONE" and not allowNoKz ? " — enable Allow NO KILLZONE" : "") +
          "\\nTQI: " + str.tostring(tqi, "#.00") + " / " + str.tostring(effectiveMinTqi, "#.00") +
          "\\nER: " + str.tostring(erValue, "#.00") + " / " + str.tostring(effectiveMinEr, "#.00") +
          "\\nVol: " + volumeState + " | ATR: " + volatilityState +
          "\\nHTF POI B/S: " + (htfBullPoiContext ? "B✓" : "B×") + " / " + (htfBearPoiContext ? "S✓" : "S×") +
          "\\nExec Zone B/S: " + (executionBullZoneOk ? "B✓" : "B×") + " / " + (executionBearZoneOk ? "S✓" : "S×") +
          "\\nKey Touch: " + (anyExistingKeyLevelTouched ? "YES" : "NO") + " | B/S " + (bullKeyReaction ? "B✓" : "B×") + "/" + (bearKeyReaction ? "S✓" : "S×")

        if miniStatusPosition == "Top Right"
            drawStatusTable(statusTopRight, statusTxt)
        else if miniStatusPosition == "Top Left"
            drawStatusTable(statusTopLeft, statusTxt)
        else if miniStatusPosition == "Bottom Right"
            drawStatusTable(statusBottomRight, statusTxt)
        else if miniStatusPosition == "Bottom Left"
            drawStatusTable(statusBottomLeft, statusTxt)
        else
            statusLabel := label.new(bar_index + 2, close, statusTxt, style = label.style_label_left, color = color.new(color.black, 20), textcolor = color.white, size = size.small)'''


def must_replace(text: str, old: str, new: str, label: str) -> str:
    if old not in text:
        raise RuntimeError(f"Required replacement marker not found: {label}")
    return text.replace(old, new, 1)


def replace_section(text: str, start_marker: str, end_marker: str, new_section: str, label: str) -> str:
    start = text.find(start_marker)
    if start == -1:
        raise RuntimeError(f"Section start marker not found: {label}")
    end = text.find(end_marker, start)
    if end == -1:
        raise RuntimeError(f"Section end marker not found: {label}")
    return text[:start] + new_section.rstrip() + "\n\n" + text[end:]


def active_counts(text: str) -> tuple[int, int]:
    version_count = 0
    indicator_count = 0
    for raw in text.splitlines():
        line = raw.strip()
        if not line:
            continue
        # //@version is intentionally a Pine directive even though it begins with //.
        if line.startswith("//@version"):
            version_count += 1
            continue
        # Other // comments should not count as active code.
        if line.startswith("//"):
            continue
        if line.startswith("indicator("):
            indicator_count += 1
    return version_count, indicator_count


def main() -> None:
    base = BASE_PATH.read_text(encoding="utf-8")
    smart_block = SMART_BLOCK_PATH.read_text(encoding="utf-8")

    if not base.startswith("//@version=6"):
        raise RuntimeError("Base file does not start with //@version=6")
    smart_versions, smart_indicators = active_counts(smart_block)
    if smart_versions or smart_indicators:
        raise RuntimeError("Smart block has an active Pine header. It must stay isolated.")

    candidate = base
    groups_marker = "// ══════════════════════════════════════════════════════════════════════════════\n// GROUPS"
    candidate = must_replace(candidate, groups_marker, HEADER_NOTE + "\n" + groups_marker, "GROUPS marker")
    candidate = must_replace(candidate, OLD_STATUS_INPUT, NEW_STATUS_INPUT, "mini status input replacement")
    candidate = must_replace(candidate, INSERT_MARKER, smart_block.rstrip() + "\n\n" + INSERT_MARKER, "smart block insertion")
    for old, new, label in REPLACEMENTS:
        candidate = must_replace(candidate, old, new, label)
    candidate = replace_section(candidate, STATUS_START_MARKER, ALERTS_MARKER, NEW_STATUS_BLOCK, "mini status panel replacement")
    candidate = candidate.replace("// End of Master SMC + SATS Sniper System v1.4", "// End of Master SMC + SATS Sniper System v1.5 SMART KEY LIQUIDITY CANDIDATE", 1)

    v_count, i_count = active_counts(candidate)
    if v_count != 1 or i_count != 1:
        raise RuntimeError(f"Candidate must contain one active version and one active indicator. Found version={v_count}, indicator={i_count}")
    for required in ['"\\nBias: "', "miniStatusPosition", "drawStatusTable", "smartAnyKeyTouched", "if obCount > 0", "if fvgCount > 0", "Smart Level Source TF"]:
        if required not in candidate:
            raise RuntimeError(f"Candidate missing required content: {required}")
    if "<!DOCTYPE html>" in candidate or "<html" in candidate:
        raise RuntimeError("Candidate contains HTML instead of raw Pine")

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(candidate, encoding="utf-8")
    print(f"Created candidate: {OUT_PATH.relative_to(ROOT)}")
    print("Open the candidate file on GitHub, use Raw, copy into TradingView, then test 3M/5M/15M.")

if __name__ == "__main__":
    main()
