#!/usr/bin/env python3
"""
Assemble Master SMC + SATS v1.5 Smart Key Liquidity Candidate.

Purpose
-------
This script safely builds a candidate Pine file from:
1. The protected v1.4 base working script.
2. The modular Block 06 Smart Key Level Engine.
3. The documented entry-confluence connection rules.

It does NOT edit the protected v1.4 base.
It writes a new candidate under 03_MASTER_CANDIDATES/.

Run from repository root:
    python pine-script/master-smc-sats/03_SCRIPT_BLOCKS/98_assemble_v1_5_candidate.py

Then open the generated candidate file on GitHub, click Raw, and copy the raw Pine code into TradingView.
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
PROJECT = ROOT / "pine-script" / "master-smc-sats"

BASE_PATH = PROJECT / "01_BASE_WORKING_VERSION" / "master-smc-sats-ravi-custom-01-v1.4-LAST-WORKING.pine"
SMART_BLOCK_PATH = PROJECT / "03_SCRIPT_BLOCKS" / "06_smart_key_level_engine.pine"
OUT_PATH = PROJECT / "03_MASTER_CANDIDATES" / "master-smc-sats-ravi-custom-01-v1.5-smart-key-liquidity-candidate.pine"

INSERT_MARKER = "// ══════════════════════════════════════════════════════════════════════════════\n// ZONE + KEY LEVEL CONFLUENCE\n// ══════════════════════════════════════════════════════════════════════════════"

OLD_ANY_TOUCH = "anyExistingKeyLevelTouched = currentSwingKeyTouched or currentPdPwPmTouched or currentPoiTouched or htfKey1Touched or htfKey2Touched"
NEW_ANY_TOUCH = "anyExistingKeyLevelTouched = currentSwingKeyTouched or currentPdPwPmTouched or currentPoiTouched or htfKey1Touched or htfKey2Touched or smartAnyKeyTouched"

OLD_BULL_END = "     (k2_obNearDir == 1 and nearLevel(k2ObLevel)) or\n     (k2_fvgNearDir == 1 and nearLevel(k2FvgLevel)))"
NEW_BULL_END = "     (k2_obNearDir == 1 and nearLevel(k2ObLevel)) or\n     (k2_fvgNearDir == 1 and nearLevel(k2FvgLevel)) or\n     smartBullKeyReaction)"

OLD_BEAR_END = "     (k2_obNearDir == -1 and nearLevel(k2ObLevel)) or\n     (k2_fvgNearDir == -1 and nearLevel(k2FvgLevel)))"
NEW_BEAR_END = "     (k2_obNearDir == -1 and nearLevel(k2ObLevel)) or\n     (k2_fvgNearDir == -1 and nearLevel(k2FvgLevel)) or\n     smartBearKeyReaction)"

OLD_END_TAG = "// End of Master SMC + SATS Sniper System v1.4"
NEW_END_TAG = "// End of Master SMC + SATS Sniper System v1.5 SMART KEY LIQUIDITY CANDIDATE"

HEADER_NOTE = """// ══════════════════════════════════════════════════════════════════════════════
// v1.5 CANDIDATE NOTE
// Generated by 03_SCRIPT_BLOCKS/98_assemble_v1_5_candidate.py
// Source base: 01_BASE_WORKING_VERSION/master-smc-sats-ravi-custom-01-v1.4-LAST-WORKING.pine
// Added: 03_SCRIPT_BLOCKS/06_smart_key_level_engine.pine
// Connection: smart key-level hooks extend, not replace, v1.4 key reactions.
// Test required in TradingView before promotion to 00_MASTER_COMPILED.
// ══════════════════════════════════════════════════════════════════════════════
"""


def must_replace(text: str, old: str, new: str, label: str) -> str:
    if old not in text:
        raise RuntimeError(f"Required replacement marker not found: {label}")
    return text.replace(old, new, 1)


def main() -> None:
    if not BASE_PATH.exists():
        raise FileNotFoundError(f"Base file not found: {BASE_PATH}")
    if not SMART_BLOCK_PATH.exists():
        raise FileNotFoundError(f"Smart block not found: {SMART_BLOCK_PATH}")

    base = BASE_PATH.read_text(encoding="utf-8")
    smart_block = SMART_BLOCK_PATH.read_text(encoding="utf-8")

    if not base.startswith("//@version=6"):
        raise RuntimeError("Base file does not start with //@version=6")
    if "indicator(" not in base[:1000]:
        raise RuntimeError("Base file does not appear to contain a Pine indicator declaration near the top")
    if "//@version" in smart_block or "indicator(" in smart_block:
        raise RuntimeError("Smart block must not contain //@version or indicator(); it is a modular block only")

    candidate = base

    # Add candidate note immediately after the indicator declaration block.
    first_section = "// ══════════════════════════════════════════════════════════════════════════════\n// GROUPS"
    if first_section in candidate:
        candidate = candidate.replace(first_section, HEADER_NOTE + "\n" + first_section, 1)
    else:
        raise RuntimeError("Could not find GROUPS section marker for candidate note insertion")

    # Insert smart key-level block before existing zone/key-level confluence logic.
    if INSERT_MARKER not in candidate:
        raise RuntimeError("Could not find ZONE + KEY LEVEL CONFLUENCE marker")
    candidate = candidate.replace(
        INSERT_MARKER,
        smart_block.rstrip() + "\n\n" + INSERT_MARKER,
        1,
    )

    # Connect smart hooks to existing v1.4 key-level logic.
    candidate = must_replace(candidate, OLD_ANY_TOUCH, NEW_ANY_TOUCH, "anyExistingKeyLevelTouched")
    candidate = must_replace(candidate, OLD_BULL_END, NEW_BULL_END, "bullKeyReaction smart OR")
    candidate = must_replace(candidate, OLD_BEAR_END, NEW_BEAR_END, "bearKeyReaction smart OR")

    # Update visible end tag only.
    candidate = candidate.replace(OLD_END_TAG, NEW_END_TAG, 1)

    # Safety checks.
    required_hooks = [
        "smartAnyKeyTouched",
        "smartBullKeyReaction",
        "smartBearKeyReaction",
        "smartBullLiquidityTouched",
        "smartBearLiquidityTouched",
    ]
    for hook in required_hooks:
        if hook not in candidate:
            raise RuntimeError(f"Missing expected smart hook after assembly: {hook}")

    if candidate.count("//@version=6") != 1:
        raise RuntimeError("Candidate must contain exactly one //@version=6 line")
    if candidate.count("indicator(") != 1:
        raise RuntimeError("Candidate must contain exactly one indicator() declaration")

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(candidate, encoding="utf-8")
    print(f"Created candidate: {OUT_PATH.relative_to(ROOT)}")
    print("Next: open this file on GitHub, click Raw, copy into TradingView, and test compile.")


if __name__ == "__main__":
    main()
