const demoTrades=[{date:'2026-05-01',pair:'XAUUSD',direction:'Buy',setup:'SMC Sweep Reversal',session:'New York',result:'Win',net:120,r:1.8,rules:true,ai:'Complete',mistakes:[],dashboardReady:true,screenshots:[]}];
let charts=[];let allTradesCache=[];let calendarDate=new Date();
function cssVar(n){return getComputedStyle(document.body).getPropertyValue(n).trim()||getComputedStyle(document.documentElement).getPropertyValue(n).trim()}
function themeColors(){return{accent:cssVar('--accent')||cssVar('--blue')||'#3b82f6',accent2:cssVar('--accent-2')||'#38bdf8',accent3:cssVar('--accent-3')||'#8b5cf6',green:cssVar('--green')||'#22c55e',red:cssVar('--red')||'#ef4444',muted:cssVar('--muted')||'#8c99ad',grid:'rgba(148,163,184,.16)'}}
async function loadTrades(){try{const r=await fetch('./data/trades.json',{cache:'no-store'});if(!r.ok)throw new Error('No exported trades yet');const d=await r.json();document.getElementById('dataStatus').textContent=`Loaded ${d.count||d.trades?.length||0} trades from dashboard export`;return Array.isArray(d.trades)&&d.trades.length?d.trades:demoTrades}catch{document.getElementById('dataStatus').textContent='Using demo data — no export file found';return demoTrades}}
function filterTrades(t){const m=document.getElementById('periodFilter').value;if(m==='all')return t;const d=m==='week'?7:31;return t.filter(x=>new Date(x.date)>=new Date(Date.now()-d*86400000))}
function money(v){const n=Number(v)||0;return`${n<0?'-':''}€${Math.abs(n).toFixed(2)}`}function pct(v){return`${(Number(v)||0).toFixed(1)}%`}function dateKey(d){return d.toISOString().slice(0,10)}function isCompletedTrade(t){return t.dashboardReady===true&&!['Incomplete','',null,undefined].includes(t.result)}function displayResult(t){return t.result||'Incomplete'}
function metrics(t){const c=t.filter(isCompletedTrade),w=c.filter(x=>String(x.result).toLowerCase().includes('win')),net=c.reduce((s,x)=>s+Number(x.net||0),0),grossWin=c.filter(x=>Number(x.net||0)>0).reduce((s,x)=>s+Number(x.net||0),0),grossLoss=Math.abs(c.filter(x=>Number(x.net||0)<0).reduce((s,x)=>s+Number(x.net||0),0)),avg=c.length?c.reduce((s,x)=>s+Number(x.r||0),0)/c.length:0,rr=c.length?c.filter(x=>x.rules===true).length/c.length*100:0,bp=Object.entries(groupSum(c,'pair','net')).sort((a,b)=>b[1]-a[1])[0]?.[0]||'-',expectancy=c.length?net/c.length:0,profitFactor=grossLoss?grossWin/grossLoss:(grossWin>0?grossWin:0);return{completed:c,wins:w,totalNet:net,avgR:avg,ruleRate:rr,bestPair:bp,winRate:c.length?w.length/c.length*100:0,expectancy,profitFactor}}
function groupSum(t,k,v){return t.reduce((a,x)=>{const key=x[k]||'Unknown';a[key]=(a[key]||0)+Number(x[v]||0);return a},{})}function groupCount(t,k){return t.reduce((a,x)=>{const vals=Array.isArray(x[k])?x[k]:[x[k]||'None'];vals.forEach(v=>a[v]=(a[v]||0)+1);return a},{})}
function destroyCharts(){charts.forEach(c=>c.destroy());charts=[]}function chartColors(v){const c=themeColors();return v.map(x=>x>=0?c.green:c.red)}
function renderCharts(t){destroyCharts();const c=themeColors(),done=t.filter(isCompletedTrade),sorted=[...done].sort((a,b)=>new Date(a.date)-new Date(b.date));let cum=0;const eq=sorted.map(x=>cum+=Number(x.net||0));charts.push(new Chart(document.getElementById('equityChart'),{type:'line',data:{labels:sorted.map(x=>x.date),datasets:[{data:eq,borderColor:c.accent,backgroundColor:hexToRgba(c.accent,.18),pointBackgroundColor:c.accent2,tension:.35,fill:true}]},options:chartOptions()}));const wl={Win:done.filter(x=>String(x.result).includes('Win')).length,Loss:done.filter(x=>String(x.result).includes('Loss')).length,BE:done.filter(x=>String(x.result).includes('Break')).length};charts.push(new Chart(document.getElementById('winLossChart'),{type:'doughnut',data:{labels:Object.keys(wl),datasets:[{data:Object.values(wl),backgroundColor:[c.green,c.red,c.accent3],borderColor:c.accent,borderWidth:1}]},options:chartOptions()}));renderBar('pairChart',groupSum(done,'pair','net'));renderBar('setupChart',groupSum(done,'setup','net'));renderBar('sessionChart',groupSum(done,'session','net'));renderBar('mistakeChart',groupCount(done,'mistakes'))}
function renderBar(id,obj){const labels=Object.keys(obj),values=Object.values(obj),c=themeColors();charts.push(new Chart(document.getElementById(id),{type:'bar',data:{labels,datasets:[{data:values,backgroundColor:values.length?chartColors(values):[c.accent],borderColor:c.accent2,borderWidth:1,borderRadius:8}]},options:chartOptions()}))}
function chartOptions(){const c=themeColors();return{responsive:true,plugins:{legend:{display:false}},scales:{x:{ticks:{color:c.muted},grid:{color:c.grid}},y:{ticks:{color:c.muted},grid:{color:c.grid}}}}}function hexToRgba(h,a){if(!h||!h.startsWith('#'))return`rgba(59,130,246,${a})`;let x=h.replace('#','');if(x.length===3)x=x.split('').map(y=>y+y).join('');const n=parseInt(x,16);return`rgba(${(n>>16)&255},${(n>>8)&255},${n&255},${a})`}
function renderTable(t){document.getElementById('tradeRows').innerHTML=t.map((x,i)=>{const net=Number(x.net||0),status=x.dashboardReady?'✅ Ready':`⚠️ ${x.calculationStatus||'Incomplete'}`,missing=x.missingRequiredFields&&x.missingRequiredFields!=='None'?x.missingRequiredFields:'';return`<tr class="trade-row" data-trade-index="${i}" title="Click to open trade story. ${missing}"><td>${x.date||''}</td><td>${x.pair||''}</td><td>${x.direction||''}</td><td>${x.setup||''}</td><td>${x.session||''}</td><td><span class="badge">${displayResult(x)}</span></td><td class="${net>=0?'profit':'loss'}">${money(net)}</td><td>${Number(x.r||0).toFixed(2)}R</td><td>${x.rules?'✅':'⚠️'}</td><td>${status}</td></tr>`}).join('');document.querySelectorAll('.trade-row').forEach(r=>r.addEventListener('click',()=>openTradeDetail(t[Number(r.dataset.tradeIndex)])))}
function monthName(d){return d.toLocaleDateString('en-US',{month:'long',year:'numeric'})}function summarizeByDay(t){return t.reduce((a,x)=>{if(!x.date)return a;const k=String(x.date).slice(0,10);if(!a[k])a[k]={count:0,net:0,trades:[]};a[k].count++;if(isCompletedTrade(x))a[k].net+=Number(x.net||0);a[k].trades.push(x);return a},{})}
function renderCalendar(t){const grid=document.getElementById('calendarGrid'),y=calendarDate.getFullYear(),m=calendarDate.getMonth(),first=new Date(y,m,1),start=new Date(first);start.setDate(first.getDate()-((first.getDay()+6)%7));const by=summarizeByDay(t),mt=t.filter(x=>{const d=new Date(x.date);return d.getFullYear()===y&&d.getMonth()===m}),mpl=mt.filter(isCompletedTrade).reduce((s,x)=>s+Number(x.net||0),0);document.getElementById('calendarTitle').textContent=monthName(calendarDate);document.getElementById('calendarPL').textContent=money(mpl);document.getElementById('calendarPL').className=mpl>=0?'profit':'loss';document.getElementById('calendarTrades').textContent=mt.length;let html=['Mon','Tue','Wed','Thu','Fri','Sat','Sun','Summary'].map(d=>`<div class="calendar-weekday ${d==='Summary'?'summary-head':''}">${d}</div>`).join('');for(let w=0;w<6;w++){let wc=0,wp=0;for(let d=0;d<7;d++){const cur=new Date(start);cur.setDate(start.getDate()+w*7+d);const info=by[dateKey(cur)]||{count:0,net:0};wc+=info.count;wp+=info.net;const cls=info.count?(info.net>0?'day-win':info.net<0?'day-loss':'day-flat'):'',out=cur.getMonth()!==m?'outside-month':'';html+=`<div class="calendar-cell ${cls} ${out}"><div class="day-num">${cur.getDate()}</div>${info.count?`<div class="day-metrics"><div class="day-trades">${info.count} trade${info.count>1?'s':''}</div><div class="day-pl ${info.net>=0?'profit':'loss'}">${money(info.net)}</div></div>`:''}</div>`}html+=`<div class="calendar-summary"><div>${wc} trade${wc===1?'':'s'}</div><div class="summary-pl ${wp>=0?'profit':'loss'}">${money(wp)}</div></div>`}grid.innerHTML=html}
function esc(s){return String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function usefulText(v,fallback){const s=String(v||'').trim();return s?s:fallback}
function pickShot(t,section){const ss=t.screenshots||[];if(!ss.length)return null;const rules={htf:['4h','1h','15m','context','before','htf'],entry:['entry','5m','3m','execution'],exit:['exit','management','close'],review:['review','mistake','extra']};const keys=rules[section]||[];return ss.find(s=>keys.some(k=>String(`${s.slotType} ${s.timeframe} ${s.category} ${s.imageType} ${s.name}`).toLowerCase().includes(k)))||null}
function allScreenshotsHtml(t){const ss=t.screenshots||[];if(!ss.length)return'<div class="empty-shot full-width">No screenshot exported for this trade. Run Ravi Full Pipeline after screenshot sync, or check Trade Screenshots database.</div>';return`<section class="shot-gallery"><h3>Uploaded Screenshots (${ss.length})</h3><div class="shot-grid">${ss.map(shotHtml).join('')}</div></section>`}
function sectionText(t,key){if(key==='htf')return usefulText(t.aiRealityCheck,'No specific HTF/context text exported.');if(key==='entry')return usefulText(t.aiReview,'No specific entry story exported.');if(key==='exit')return 'No separate exit/management analysis exported yet. Use uploaded exit screenshot and AI review notes above until the AI prompt is upgraded for dedicated exit analysis.';if(key==='review')return usefulText([t.aiMistakeDiagnosis,t.aiFutureRules].filter(Boolean).join('\n\n'),'No specific mistake/future-rule text exported.');return''}
function storyBlocks(t){const chunks=[['htf','HTF Context'],['entry','Entry Story'],['exit','Exit / Management'],['review','Mistakes & Future Rules']];return chunks.map(([key,title])=>{const shot=pickShot(t,key);return`<section class="story-block"><div class="story-text"><h3>${title}</h3><p>${esc(sectionText(t,key))}</p></div>${shot?shotHtml(shot):'<div class="story-shot empty-shot">No matching screenshot for this section</div>'}</section>`}).join('')}
function shotUrl(s){return s.thumbnailUrl||s.driveUrl||''}
function shotHtml(s){const img=shotUrl(s);return`<div class="story-shot"><div class="shot-label">${esc(s.slotType||s.category||'Screenshot')} ${s.timeframe?`· ${esc(s.timeframe)}`:''}</div>${img?`<img class="zoomable-shot" src="${esc(img)}" alt="${esc(s.name||'Screenshot')}" loading="lazy" data-title="${esc(s.slotType||s.category||'Screenshot')} ${s.timeframe?`· ${esc(s.timeframe)}`:''}" onerror="this.style.display='none';this.nextElementSibling.style.display='block'"/>`:''}<div class="shot-fallback" style="display:${img?'none':'block'}">Image preview unavailable. Run Ravi Full Pipeline to refresh Drive image links.</div></div>`}
function ensureDetailModal(){if(document.getElementById('tradeDetailModal'))return;document.body.insertAdjacentHTML('beforeend',`<div id="tradeDetailModal" class="trade-modal"><div class="trade-modal-card"><button id="closeTradeModal" class="modal-close">×</button><div id="tradeDetailContent"></div></div></div>`);document.getElementById('closeTradeModal').addEventListener('click',closeTradeDetail);document.getElementById('tradeDetailModal').addEventListener('click',e=>{if(e.target.id==='tradeDetailModal')closeTradeDetail()})}
function ensureImageLightbox(){if(document.getElementById('imageLightbox'))return;document.body.insertAdjacentHTML('beforeend',`<div id="imageLightbox" class="image-lightbox"><button id="closeImageLightbox" class="modal-close image-close">×</button><div class="image-lightbox-title" id="imageLightboxTitle"></div><img id="imageLightboxImg" alt="Expanded screenshot"/></div>`);document.getElementById('closeImageLightbox').addEventListener('click',closeImageLightbox);document.getElementById('imageLightbox').addEventListener('click',e=>{if(e.target.id==='imageLightbox')closeImageLightbox()})}
function openImageLightbox(src,title){ensureImageLightbox();document.getElementById('imageLightboxImg').src=src;document.getElementById('imageLightboxTitle').textContent=title||'Screenshot';document.getElementById('imageLightbox').classList.add('open')}
function closeImageLightbox(){document.getElementById('imageLightbox')?.classList.remove('open')}
function bindZoomableShots(){document.querySelectorAll('.zoomable-shot').forEach(img=>img.addEventListener('click',e=>{e.stopPropagation();openImageLightbox(img.src,img.dataset.title)}))}
function openTradeDetail(t){ensureDetailModal();const d=document.getElementById('tradeDetailContent');d.innerHTML=`<div class="detail-head"><div><p class="eyebrow">Trade Story Review</p><h2>${esc(t.name||t.id)}</h2><p>${esc(t.date)} · ${esc(t.pair)} · ${esc(t.direction)} · ${esc(t.session)} · ${esc(t.setup)}</p></div><div class="detail-result ${Number(t.net||0)>=0?'profit':'loss'}">${money(t.net||0)}<small>${Number(t.r||0).toFixed(2)}R</small></div></div><div class="detail-kpis"><span>Entry: <b>${esc(t.entryPrice||'-')}</b></span><span>Exit: <b>${esc(t.exitPrice||'-')}</b></span><span>Lot: <b>${esc(t.lotSize||'-')}</b></span><span>SL: <b>${esc(t.stopLoss||'-')}</b></span><span>TP: <b>${esc(t.takeProfit||'-')}</b></span><span>AI: <b>${esc(t.ai||'-')}</b></span></div>${allScreenshotsHtml(t)}<div class="story-wrap">${storyBlocks(t)}</div>`;document.getElementById('tradeDetailModal').classList.add('open');bindZoomableShots()}
function closeTradeDetail(){document.getElementById('tradeDetailModal')?.classList.remove('open')}
async function render(){if(!allTradesCache.length)allTradesCache=await loadTrades();const trades=filterTrades(allTradesCache),m=metrics(trades);document.getElementById('netProfit').textContent=money(m.totalNet);document.getElementById('winRate').textContent=pct(m.winRate);document.getElementById('totalTrades').textContent=allTradesCache.length;document.getElementById('averageR').textContent=`${m.avgR.toFixed(2)}R`;document.getElementById('bestPair').textContent=m.bestPair;document.getElementById('ruleRate').textContent=pct(m.ruleRate);const pf=document.getElementById('profitFactor');if(pf)pf.textContent=Number(m.profitFactor||0).toFixed(2);const ex=document.getElementById('expectancy');if(ex)ex.textContent=money(m.expectancy||0);renderCharts(trades);renderTable(trades);renderCalendar(allTradesCache)}
document.getElementById('themeSelect').addEventListener('change',e=>{document.body.dataset.theme=e.target.value;localStorage.setItem('raviDashboardTheme',e.target.value);render()});document.getElementById('periodFilter').addEventListener('change',render);document.getElementById('prevMonth').addEventListener('click',()=>{calendarDate.setMonth(calendarDate.getMonth()-1);renderCalendar(allTradesCache)});document.getElementById('nextMonth').addEventListener('click',()=>{calendarDate.setMonth(calendarDate.getMonth()+1);renderCalendar(allTradesCache)});document.querySelectorAll('.tab-btn').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tab-btn').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.tab-section').forEach(s=>s.classList.remove('active'));btn.classList.add('active');document.getElementById(`tab-${btn.dataset.tab}`).classList.add('active')}));document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeImageLightbox();closeTradeDetail()}});const savedTheme=localStorage.getItem('raviDashboardTheme')||'dark';document.body.dataset.theme=savedTheme;document.getElementById('themeSelect').value=savedTheme;render();